version: 2
updates:
  # - package-ecosystem: "npm"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "weekly"

  # # Enable version updates for Docker in the frontend directory (if applicable)
  # - package-ecosystem: "docker"
  #   directory: "/frontend"
  #   schedule:
  #     interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Enable version updates for Docker in the backend directory (if applicable)
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"