module.exports = {
    disableEmoji: false,
    list: [
        'Add',
        'BasicFix',
        'CodeQuality',
        'Comment',
        'Config',
        'Conflicts',
        'CriticalFix',
        'Design',
        'Docs',
        'Files',
        'Fix',
        'Fun',
        'Ignore',
        'Idea',
        'Improve',
        'Log',
        'LogAdd',
        'LogDelete',
        'Move',
        'Package',
        'Performance',
        'Refactor',
        'Review',
        'Security',
        'Style',
        'Test',
        'Tracking',
        'Update',
        'WIP',
        'Wording',
    ],
    maxMessageLength: 64,
    minMessageLength: 3,
    questions: ['type', 'subject'],
    scopes: ['None', 'API', 'Feature', 'Setup', 'Type Definitions'],

    types: {
        Add: { description: 'Add new features', emoji: '✨', value: 'Add' },
        BasicFix: { description: 'Bug fixes and basic problem-solving', emoji: '🛠️', value: 'BasicFix' },
        CodeQuality: { description: 'Code quality and style', emoji: '💻', value: 'CodeQuality' },
        Comment: { description: 'Add new ideas and comments', emoji: '💡', value: 'Comment' },
        Config: { description: 'Config change', emoji: '⚙', value: 'Config' },
        Conflicts: { description: 'Conflicts', emoji: '💢', value: 'Conflicts' },
        CriticalFix: { description: 'Fix a critical bug', emoji: '🚑', value: 'CriticalFix' },
        Design: { description: 'Design changes only', emoji: '🎨', value: 'Design' },
        Docs: { description: 'Documentation', emoji: '📚', value: 'Docs' },
        Files: { description: 'Folder manipulation', emoji: '🗂️', value: 'Files' },
        Fix: { description: 'Bug fixes', emoji: '🐛', value: 'Fix' },
        Fun: { description: 'Code that was fun to write', emoji: '🍻', value: 'Fun' },
        Ignore: { description: '.gitignore addition', emoji: '🙈', value: 'Ignore' },
        Idea: { description: 'Implement and code idea', emoji: '💡', value: 'Idea' },
        Improve: { description: 'Feature improvements', emoji: '👍', value: 'Improve' },
        Log: { description: 'Logging and tracking', emoji: '📊', value: 'Log' },
        LogAdd: { description: 'Add log', emoji: '🔊', value: 'LogAdd' },
        LogDelete: { description: 'Log deleted', emoji: '🔇', value: 'LogDelete' },
        Move: { description: 'File movement', emoji: '🚚', value: 'Move' },
        Package: { description: 'Add new dependency', emoji: '📦', value: 'Package' },
        Performance: { description: 'Performance improvements', emoji: '🚀', value: 'Performance' },
        Refactor: { description: 'Refactoring', emoji: '♻️', value: 'Refactor' },
        Review: { description: 'Code reading and questions', emoji: '🧐', value: 'Review' },
        Security: { description: 'Security', emoji: '🛡️', value: 'Security' },
        Style: { description: 'Lint error fixes and code style fixes', emoji: '👕', value: 'Style' },
        Test: { description: 'Fix/improve testing and CI', emoji: '🧪', value: 'Test' },
        Tracking: { description: 'Add analytics or tracking code', emoji: '📈', value: 'Tracking' },
        Update: { description: 'Update dependency packages, etc.', emoji: '🆙', value: 'Update' },
        WIP: { description: 'WIP (Work in Progress)', emoji: '🚧', value: 'WIP' },
        Wording: { description: 'Fix wording', emoji: '📝', value: 'Wording' }
    },

    commitMessageFormat: (emoji, value , subject) => `${emoji} ${value}: ${subject}`
};
