name: "🐞 Bug Report"
description: "Report an issue or unexpected behavior."
title: "🐞 Bug: [Short description of the issue]"

body:
  - type: markdown
    attributes:
      value: |
        ## Bug Description
        <!-- Briefly describe the issue encountered. -->
        <!-- Include details on what you expected to happen vs. what actually occurred. -->

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Clearly list the steps to reproduce the bug."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe error '...'
    validations:
      required: true

  # - type: input
  #   id: version
  #   attributes:
  #     label: "Version"
  #     description: "Specify the version of software or system where this bug occurs."
  #     placeholder: "e.g., v2.0.1"
  #   validations:
  #     required: true

  # - type: textarea
  #   id: environment
  #   attributes:
  #     label: "Environment"
  #     description: "Describe your operating system, browser, or other relevant environment details."
  #     placeholder: |
  #       - OS: e.g., Windows 11
  #       - Browser: e.g., Chrome 120.0
  #   validations:
  #     required: false

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any additional context or screenshots about the issue here."
    validations:
      required: false
